# Generated by Django 4.2.6 on 2023-10-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('username', models.TextField(max_length=25)),
                ('name', models.TextField(max_length=50)),
                ('image', models.ImageField(upload_to='images/profile')),
                ('state', models.TextField()),
            ],
        ),
    ]
